### ISSUE TITLE
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 

### ISSUE THREAD

**Issue by vinitamehlawat** [mhoban/haplonet#1]
Hi Mhoban

Greetings, I am using you Rscript for creating the haplotype network for SARS-CoV2 data. I am having a aligned fasta file and one metadata file which I am using to run this script. I used _Rscript haplonet.r file.fasta metada.tsv_ but it gives following error: 

**loading libraries (can take a sec)...
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 525 did not have 28 elements
Calls: read.table -> scan
Execution halted**

I would really appreciate you time and effor kindly help me out
Thank you very much in advance !
vinita

**Comment by mhoban** [comment]
Hi Vinita-

Thanks for using my script! If you're willing to share your data (or just a pared-down version of it) I could look into it and see what's going wrong. I haven't been actively maintaining this script lately so some of the libraries it depends on may have changed and caused things to break.

**Comment by vinitamehlawat** [comment]
Hi Mhoban
Thanks for your prompt reply. I am sharing my fasta file and metadata file
for your reference. Kindly have a look and help me to plot the network for
this kind of data.

Thank you very much !

Best
Vinita
 1624288258184.metadata.tsv
<https://drive.google.com/file/d/19zn9zzv44mN1Gm9-5i1xu9U9aIRi84AO/view?usp=drive_web>
 alignment.fasta
<https://drive.google.com/file/d/18AiwjXX-BlER_ZtI9cSskRA6TW8nSDii/view?usp=drive_web>

**Comment by mhoban** [comment]
I looked into this a little bit and there are a few problems that jump out immediately. First, line 1391 in the metadata file seems to be incomplete, so that's the source of your error message. Delete that line and it's able to proceed. Second, in order for the script to work, your metadata file has to have a column called `id` that matches up with the fasta identifiers. I think in your data the first column `strain` can just be renamed to `id`. The last issue is potentially a bigger one and unfortunately I don't have the time to dig into it and see if I can make it work.

When I wrote this script, I wrote it with alignments of Sanger-sequenced markers in mind (on the order of 500-1500bp in length). I see that your sequences are all quite long (almost ~30kb). I can't say that the script *won't* work with alignments that long, but I do know the computation will be very slow. Feel free to try to make the adjustments I mentioned above and see if you can get it to run, but I suspect it'll take a really long time, if it works at all. If you can trim your alignment to a shorter sequence length (i.e. some region that's more variable than others), you might have better luck. 

Let me know if you do try this and if you get any other out-of-place error messages. As I said in my first reply, I haven't really maintained this for a while and some of the dependency packages have since changed, which might also break things here and there. Feel free to fork this repo and make changes on your own as well!

**Comment by vinitamehlawat** [comment]
Hi Mhoban

Thank you very much for your prompt responses and helping me . As per your
suggestion I have chnages the 1 column in my metadat file and named it as
*id* and I also take a set of block of short alignment i.e. for 1031 seq
are there now and I rerun your script but this time after running for
around 10 min it is giving the different error:
**loading libraries (can take a sec)...

Attaching package: ‘stats’

The following objects are masked from ‘package:dplyr’:

filter, lag

Error in table(hap = as.numeric(as.character(ind)), pop = samples[values, :
all arguments must have the same length**


I am also attaching the alignment file (1031 seq this time) and
metadata file for this alignment


** I have also tried with the minimum dataset which is having 124 sequences
and tried to run this script but it is showing the same error message. I
would really appreciate your valuable time if you could please help me for
this script


Best

Vinita
 alignment.fasta
<https://drive.google.com/file/d/1AwaXDerioUGKDwrPMRKMgNVlnKw0J4Yf/view?usp=drive_web>

**Comment by mhoban** [comment]
Hi, it looks like this alignment is still ~30kb long. I was able to get it to work by doing the following:

 - I trimmed the alignment to 1.5kb. I did this arbitrarily, but you would probably want to make some informed decisions about how to do this. It may be obvious, but when I say 'kb', I'm referring to kilobases, i.e. the length of the DNA sequences, not kilobytes (the size of the file).

 - I made sure the FASTA id's matched up with the `id` column in the metadata. To do this, I had to trim off everything after the first '|' in the fasta ID's, because some of them looked like this:

   \>hCoV-19/India/MH-1-27/2020|EPI_ISL_413522|2020-01-27

   \>hCoV-19/India/MH-1-31/2020|EPI_ISL_413523|2020-01-31

   ...

   And the `id` field looks like >hCoV-19/India/MH-1-27/2020, >hCoV-19/India/MH-CCMB-NIV2/2020, etc.

- I deleted the first sequence in the alignment because it had a different id that didn't match anything in the metadata
- Make sure to use the `--field` argument to specify which field you want to color haplotypes by. It looks like the `location` field is probably the one you want to use given your dataset?

I also had to make a couple small code changes because some of the libraries I use have updated and behave differently than before. I got rid of the dependency on the `beyonce` package. It now defaults to the big color palette. Do a pull on the repository and you should get those updates. I was able to get it to run using the following commands, where the file 'trimmed_alignment.fasta' is your alignment trimmed to 1.5kb, anything after the '|' cut off the IDs, and the sequence called `>NC_045512.2 sars_cov2 isolate Wuhan-Hu-1, complete genome_1` deleted. The file 'samples.tsv' is your metadata file with the `strain` field renamed as `id`:

```bash
$ Rscript haplonet.r timmed_alignment.fasta samples.tsv --field=location
```

A couple of caveats 

- this might only work on a Mac, since that's where I wrote it and I made no effort to make it cross-platform
- your alignment has many haplotypes (~330 or so), which will make the network plot very busy and hard to read. 
- you'll have to rearrange many many circles to get a legible haplotype network
- Make sure you've got the latest version of the `pegas` package installed. Don't use my hacked version, since the main package has since fixed the problems I tried to fix. Also make sure you've got the latest version of `docopt`.

Good luck! I've reached the limit of the time I have available to help with this. The code is there, though, so you should be able to play around with it and get it to work for you eventually!

**Comment by vinitamehlawat** [comment]
Hi Mhoban

Thnak you very much for your such an eloborative explanation. I figured out that these are the _Viral genome_ and we can't shorten them from 30kb to  ~2kb but I tried your script for samller protein sequences and it works for me. 

Again thnks!
