### ISSUE TITLE
Can you give an example of the command to run the script non-interactively?

### ISSUE THREAD

**Issue by vmkalbskopf** [mhoban/haplonet#2]
I'd like to run this script on 20 alignment files using a bash loop. But I can't figure out how to pass the legend coordinates and leave the nodes in their default positions so it can run non-interactively.

Can you help by giving an example of what that command might look like?

**Comment by mhoban** [comment]
The script isn't actually set up to run non-interactively as it's written.  But you should be able to modify the code to do that without too much trouble. The main change would be to comment out the line that calls `replot()` (looks like line 192). You'll also need to modify the initial plot to save directly to a pdf rather than popping up a window. Take a look near the bottom where it saves the legend for an example of how to do that.  It may be as simple as changing line 185 to say `quartz(type="pdf",file="plot.pdf",bg="white")` but you'll have to be careful not to overwrite the output PDFs if you're running this against multiple alignments.
